name: Deploy
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 142.93.181.16
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD | urldecode }}
        port: 22
        script: |
          cd project1
          source venv/bin/activate
          git pull
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
