name: Deploy
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Execute remote SSH commands using password
      run: |
        cd project1
        source venv/bin/activate
        git pull
        python manage.py migrate
        python manage.py collectstatic --noinput
        supervisorctl restart all
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
