name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: 142.93.181.16
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/project1
            source /root/venv/bin/activate
            git pull
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo supervisorctl restart all
